export const INVALIDATION_MAP = {
  Place: {
    add: [["Places"], ["PlacesDropdown"]],
    update: [
      ["Places"],
      ["PlacesDropdown"],
      ["Observations"],
      ["Observation"],
      ["Diaries"],
      ["Diary"],
      ["DashboardStat"],
    ],
    delete: [
      ["Places"],
      ["PlacesDropdown"],
      ["Observations"],
      ["Observation"],
      ["Diaries"],
      ["Diary"],
      ["DashboardStat"],
    ],
  },
  Observation: {
    add: [
      ["Observations"],
      ["Diaries"],
      ["Diary"],
      ["DiaryDetail"],
      ["Places"],
      ["Place"],
      ["Stat"],
      ["Checklist"],
      ["Activity"],
      ["SpeciesDropdown"],
      ["Rating"],
      ["RatingCompare"],
      ["RatingCompareHeader"],
      ["DashboardStat"],
      ["BirdOfDay"],
    ],
    update: [
      ["Observations"],
      ["Observation"],
      ["Diaries"],
      ["Diary"],
      ["DiaryDetail"],
      ["Places"],
      ["Place"],
      ["Stat"],
      ["Activity"],
      ["Checklist"],
      ["SpeciesDropdown"],
      ["Rating"],
      ["RatingCompare"],
      ["RatingCompareHeader"],
      ["DashboardStat"],
      ["BirdOfDay"],
    ],
    delete: [
      ["Observations"],
      ["Diaries"],
      ["Diary"],
      ["DiaryDetail"],
      ["Places"],
      ["Place"],
      ["Stat"],
      ["Checklist"],
      ["Activity"],
      ["SpeciesDropdown"],
      ["Rating"],
      ["RatingCompare"],
      ["RatingCompareHeader"],
      ["DashboardStat"],
      ["BirdOfDay"],
    ],
  },
  Diary: {
    add: [["Diaries"], ["Places"], ["DashboardStat"]],
    update: [
      ["Diaries"],
      ["Diary"],
      ["Observation"],
      ["Place"],
      ["DashboardStat"],
    ],
    delete: [
      ["Diaries"],
      ["Diary"],
      ["DiaryDetail"],
      ["Observations"],
      ["Observation"],
      ["Place"],
      ["Stat"],
      ["Checklist"],
      ["Activity"],
      ["SpeciesDropdown"],
      ["Rating"],
      ["RatingCompare"],
      ["RatingCompareHeader"],
      ["DashboardStat"],
      ["BirdOfDay"],
    ],
  },
  Profile: {
    update: [["Rating"], ["userProfile"], ["RatingCompareHeader"]],
  },
};
